<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Label="Framework References">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\core\yggdrasil.Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>
</Project>
