<Project>
  <PropertyGroup Label="C#">
		<TargetFramework>net10.0</TargetFramework>

		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AnalysisLevel>latest</AnalysisLevel>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591;CA1054;CA1056</NoWarn>
	</PropertyGroup>
  <PropertyGroup Label="Code Analysis">
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisModeDesign>Default</AnalysisModeDesign>
    <AnalysisModeDocumentation>Recommended</AnalysisModeDocumentation>
    <AnalysisModeGlobalization>Recommended</AnalysisModeGlobalization>
    <AnalysisModeInteroperability>Recommended</AnalysisModeInteroperability>
    <AnalysisModeMaintainability>Recommended</AnalysisModeMaintainability>
    <AnalysisModeNaming>Default</AnalysisModeNaming>
    <AnalysisModePerformance>Minimum</AnalysisModePerformance>
    <AnalysisModeReliability>Recommended</AnalysisModeReliability>
    <AnalysisModeSecurity>Default</AnalysisModeSecurity>
    <AnalysisModeUsage>Default</AnalysisModeUsage>
  </PropertyGroup>
</Project>
