<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\..\buildingblocks\core\yggdrasil.Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>
</Project>
