// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using yggdrasil.Modules.Profiles.Data;

#nullable disable

namespace yggdrasil.Modules.Profiles.Data.Migrations
{
    [DbContext(typeof(ProfilesModuleDbContext))]
    [Migration("20260929200744_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profiles")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("yggdrasil.Modules.Profiles.Domain.GameProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<int>("DataVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("data_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("AccountId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_account_id_game_id");

                    b.ToTable("profiles", "profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
