<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\publicapis\yggdrasil.PublicApis.csproj" />
  </ItemGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup Label="Global Usings">
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
